apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kind-superuser-rolebinding
roleRef:
  kind: Role
  name: kind-superuser-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
