apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: olo-controller-manager-rolebinding
roleRef:
  kind: Role
  name: olo-controller-manager-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: olo-controller-manager
