apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: olo-controller-manager-role
rules:
  - apiGroups:
      - ""
      - coordination.k8s.io
    resources:
      - configmaps
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments/finalizers
      - statefulsets
    verbs:
      - update
  - apiGroups:
      - apps.openliberty.io
    resources:
      - openlibertyapplications
      - openlibertyapplications/finalizers
      - openlibertyapplications/status
    verbs:
      - '*'
  - apiGroups:
      - apps.openliberty.io
    resources:
      - openlibertydumps
      - openlibertydumps/finalizers
      - openlibertydumps/status
    verbs:
      - '*'
  - apiGroups:
      - apps.openliberty.io
    resources:
      - openlibertytraces
      - openlibertytraces/finalizers
      - openlibertytraces/status
    verbs:
      - '*'
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumeclaims
      - secrets
      - serviceaccounts
      - services
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - '*'
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
      - imagestreamtags
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - '*'
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - '*'
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - '*'
